### ISSUE TITLE
Thumbnail Preview not working (FFMPEG)

### ISSUE THREAD

**Issue by IIIPeAceIII** [Moodkiller/MPV-Made-Easy#12]
It shows thumbnail preview for all video files except mkv, only want to use ffmpeg. How to fix it?

**Comment by OmiChrome** [comment]
> It shows thumbnail preview for all video files except mkv, only want to use ffmpeg. How to fix it?

does not work for me  :(

**Comment by OmiChrome** [comment]
![image](https://user-images.githubusercontent.com/108952834/189443452-99a1fe53-184d-4fde-bced-6a41a25f0bff.png)
see

**Comment by Moodkiller** [comment]
Hi, thanks for the reports. I've swapped out the thumbnail generator with `thumbfast` instead to go with a new UI. Please update to this version and let me know if you still have the same issue. Will close this for now.
