### ISSUE TITLE
Material-Design-Iconic-Font.ttf is missing

### ISSUE THREAD

**Issue by JulianDominic** [Moodkiller/MPV-Made-Easy#13]
This is my first time using mpv so this is a completely fresh install.

I think `Material-Design-Iconic-Font.ttf` is missing from the fonts folder?

In `mpv.conf` when `'Source Sans Pro'` is being used, all of the buttons are just a blank rectangle box.

I installed `Material-Design-Iconic-Font.ttf` from another source, and set `osd-font='Material-Design-Iconic-Font'` to get the buttons to render correctly.

**Comment by Moodkiller** [comment]
You are right, good catch and good workaround. 

I see the gitignore file is set to ignore font files, which as far as best practices go, is not a bad idea... but, there are fonts in the /font/ directory from the first commit. Will add `Material-Design-Iconic-Font.ttf` to the next commit
