### ISSUE TITLE
On screen controller not showing

### ISSUE THREAD

**Issue by WillsShadow** [Moodkiller/MPV-Made-Easy#14]
This might not really be an issue at all and I'm just not doing things right but I've been trying to get the controller to be visible for a few hours now with no success

Am I missing something from just changing this 
osc=no
to osc=yes ?	
Or is there a specific conf file I'm not seeing that I need to edit to have the on screen controller

**Comment by Moodkiller** [comment]
No problem, thanks for mentioning it. Can you try the `dev` branch and let me me know if it still have the same issue?

Alternatively, [edit this file](https://github.com/Moodkiller/MPV-Made-Easy/commit/5fde28a1c63e4dab1195ab1d2bd0bd27be2a8bb6#diff-1470f58d8c564818cd657452f7b9df799307a64f6ab4b0aaacc2cac16a9ad740) to match the changes and test again. I'm not sure when MPV got rid of this property.

If all of those fail, then check to make sure you have the [script-opts/osc.conf](https://github.com/Moodkiller/MPV-Made-Easy/blob/dev/script-opts/osc.conf) file installed.

**Comment by Tempest32** [comment]
Why are osc.conf and modernf.conf the same in script-opts

**Comment by Moodkiller** [comment]
Was left over by mistake - The OSC is customised with the `modernf.conf` file if using the `modernf.conf` interface.

**Comment by WillsShadow** [comment]
I tried to do the changes that you suggested but I'm not exactly sure I did them properly so I simply downloaded the newest version and it seems to be working fine now
