### ISSUE TITLE
More Information in OSC.

### ISSUE THREAD

**Issue by Tempest32** [Moodkiller/MPV-Made-Easy#16]
Hello, thanks for the update.
While the new thumbnail generator is great and the OSC looks sleek, its missing some at a glace info compared to the previous OSC.
![image](https://github.com/Moodkiller/MPV-Made-Easy/assets/59329018/68c3d610-90c1-427a-8bee-fe0ca6502b20)
![image](https://github.com/Moodkiller/MPV-Made-Easy/assets/59329018/b3e6dee4-dee6-40d9-8d6e-4c00c2e7d6c3)

Is it possible to show this info in the new osc (size, video dimensions, codecs, audio channels etc)

And also the number of audio and subtitle tracks in the file.

**Comment by Moodkiller** [comment]
Thanks for the feedback. It shouldn't be too tricky to add the filesize, video dimensions, codecs, audio channels back to the title. That said, it would probably be best to do this via options that the user can configure? 

The track numbers / quantity might be little more tricky as it would affect the layout (it does show the track count if you hover over it BUT there is bug where the track name gets cut off). Will see what I can come up with

**Comment by Moodkiller** [comment]
@Tempest32 - dont know if you would be interested but I've pushed some changes to the dev branch which has some changes to the OSD: 

1. If you have the layout of modernf set to "original", you should get the full file name, size, video res, audio codecs and current playlist location now
2. The ugly scroll bars that appear when seeking or changing the volume have been disabled
3. Set the font to be the same as set in modernf interface
4. Made the seek bar a tad taller for easier mouse placement

TODO
1. Add track count to audio and subtitle icons
2. Add the missing buttons 
3. Add the remaining layout for the "mid" and "reduced" layouts

<img width="1435" alt="image" src="https://github.com/Moodkiller/MPV-Made-Easy/assets/11341653/be2a439a-650a-469c-ae55-3a3a12c78b5b">

**Comment by Tempest32** [comment]
@Moodkiller, love all the information in the OSD now! Thanks for the effort.

**Comment by Moodkiller** [comment]
Implementation: https://github.com/Moodkiller/MPV-Made-Easy/pull/18/commits/70d3597e89e04cfc9c810bc4e7ca7dbe5e726a24
