### ISSUE TITLE
Updater.ps1 missing

### ISSUE THREAD

**Issue by ZummiGummi** [Moodkiller/MPV-Made-Easy#2]
It looks like the latest commit deleted Updater.ps1.

**Comment by Moodkiller** [comment]
More like I included it by accident the first time around. Ideally it's best to get the required MPV build from the link at the bottom of the readme, but I have changed it around to include and updated .bat and the requested updater.ps1 with the latest commit https://github.com/Moodkiller/MPV-Made-Easy/commit/17da8bb2ee7d6caa4eef2a06a655daa5849aec35
