### ISSUE TITLE
Thumbnail problem since update :/

### ISSUE THREAD

**Issue by ModernLobby** [Moodkiller/MPV-Made-Easy#4]
Hey 

So i used your MPV made easy setup and i saw you update it but since i'm a little noob with it the thumbnail don't work with the new config file :/
![image](https://user-images.githubusercontent.com/23289966/73712914-ddd29800-470b-11ea-8c37-da7b3200291f.png)

Here if it can help 

Thanks in advance

**Comment by Moodkiller** [comment]
Thanks for this, latest release / commit from Golumpa has solved this issue.
